apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: replace-path
  namespace: default
spec:
  replacePath:
    path: /
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: replace-path
  namespace: test
spec:
  replacePath:
    path: /
