version: "3.3"

services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
      # containers that do not have a traefik.enable=true label are ignored from the resulting routing configuration.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/traefik.yml:/etc/traefik/traefik.yml"
      - "$PWD/certificates/whoami.local.crt:/whoami.local.crt"
      - "$PWD/certificates/whoami.local.key:/whoami.local.key"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"

