version: "3.3"

services:
  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      # containers that do not have a traefik.enable=true label are ignored from the resulting routing configuration.
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.tls.cert=/whoami.local.crt"
      - "--providers.docker.tls.key=/whoami.local.key"
      - "--providers.docker.endpoint=tcp://socat:2375"
      - "--providers.docker.watch=true"
      - "--entrypoints.web.address=:80"
      #- "--configFile=/etc/traefik/config.yaml"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/certificates/whoami.local.crt:/whoami.local.crt"
      - "$PWD/certificates/whoami.local.key:/whoami.local.key"
      #- "$PWD/config.yaml/:/etc/traefik/config.yaml"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami.local`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.middlewares.replacepathregex.replacepathregex.regex=^/whoami.local/(.*)"
      - "traefik.http.middlewares.replacepathregex.replacepathregex.replacement=/$$1"
      - "traefik.http.routers.whoami.middlewares=replacepathregex"

