debug: true
logLevel: DEBUG

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
